spring.application.name=SpringBootMockTestDemo

spring.datasource.url=jdbc:postgresql://localhost:5432/abesdb2
spring.datasource.username=postgres
spring.datasource.password=Sameer581*@#
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto= update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect